<?php

/**
 * @file
 * Primary module hooks for Дополнительные поля module.
 */

function print_field_info($setting_name): void
{
    $config = \Drupal::config('additional_field.settings');
    $my_setting = $config->get($setting_name);
    $table_values = $config->get('table');
    $table_arr = [];

    if (!empty($table_values)) {
        foreach ($table_values as $key => $value) {
            $table_arr[$value['variable_name']] = $value['variable_value'];
        }
    }
    if (!empty($my_setting)) {
        return $my_setting;
    } elseif (!empty($table_arr[$setting_name])) {
        return $table_arr[$setting_name];
    }
}

function additional_field_preprocess(&$variables, $hook)
{
    $form_config = \Drupal::config('additional_field.settings');
    $variables['get_phone'] = $form_config->get('phone_number');
    $variables['get_mail'] = $form_config->get('mail');
    $variables['get_viber'] = $form_config->get('viber');
    $variables['get_whatsapp'] = $form_config->get('whatsapp');
    $variables['get_vk'] = $form_config->get('vk');
    $variables['get_tg'] = $form_config->get('telegram');
    $variables['get_index'] = $form_config->get('index');
    $variables['get_city'] = $form_config->get('city');
    $variables['get_street'] = $form_config->get('street');
    $variables['get_house'] = $form_config->get('house');
    $variables['get_additional'] = $form_config->get('additional_info');

    $table_values = $form_config->get('table');
    $table_arr = [];
    if (!empty($table_values)) {
        foreach ($table_values as $key => $value) {
            if (!empty($value['variable_name'])) {
                $variables[$value['variable_name']] = $value['variable_value'];
            }
        }
    }
}